[build]
  publish = "dist"
  command = "npm run build"

# SPA routing - this handles all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specific redirects for sections
[[redirects]]
  from = "/casino"
  to = "/#casinos"
  status = 302

[[redirects]]
  from = "/bonuses"
  to = "/#bonuses"
  status = 302

[[redirects]]
  from = "/reviews"
  to = "/#reviews"
  status = 302

[[redirects]]
  from = "/news"
  to = "/#news"
  status = 302

[[redirects]]
  from = "/faq"
  to = "/#faq"
  status = 302

# Legacy redirects
[[redirects]]
  from = "/article/*"
  to = "/articles/:splat"
  status = 301

[[redirects]]
  from = "/blog/*"
  to = "/articles/:splat"
  status = 301

[build.environment]
  NODE_VERSION = "18"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache headers for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"